
excluded: 
  - Carthage
  - Pods
line_length:
  - 125
disabled_rules:
  - file_length
  - nesting
  - opening_brace
  - identifier_name
  - type_body_length
  - trailing_whitespace
opt_in_rules:
  - closure_end_indentation
  - closure_spacing
  - conditional_returns_on_newline
  - empty_count
  - explicit_init
  - first_where
  - force_unwrapping
  - operator_usage_whitespace
  - overridden_super_call
  - redundant_nil_coalescing
  - redundant_optional_initialization
  - redundant_void_return
  - sorted_imports
  - switch_case_on_newline
trailing_comma:
  mandatory_comma: true
