language: objective-c
osx_image: xcode9.4

matrix:
  include:
    - os: osx
      env: ACTION=test
    - os: osx
      env: ACTION=lint
    - os: osx
      env: ACTION=carthage

script:
  - make run-$ACTION